/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: Plataforma Transaccional Distribuida Event-Driven
   Architecture: CQRS + Event Sourcing
   Stack: csharp + dotnet-aspnetcore + entity-framework-core
   Generated by gherkin-ai CLI v2.6.1
   ========================================================================== */

import { z } from 'zod';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}

export interface Event1 extends IDomainEvent {
  eventType: 'SystemReceives10IdenticalOrderEventsSameIdempotencyKeyEvent';
  payload: {

  };
}

export interface Event2 extends IDomainEvent {
  eventType: 'ProcessingOrderEventsEvent';
  payload: {

  };
}

export interface Event3 extends IDomainEvent {
  eventType: 'Ignores9DuplicateEventsIdempotentlyEvent';
  payload: {

  };
}

export interface Event4 extends IDomainEvent {
  eventType: 'OrderProcessedEventOnlyOnceEvent';
  payload: {

  };
}

export interface Event5 extends IDomainEvent {
  eventType: 'ConcurrentEventsAreDistributedAmongInstancesEvent';
  payload: {

  };
}

export interface Event6 extends IDomainEvent {
  eventType: 'LockingMechanismPreventsRaceConditionsEvent';
  payload: {

  };
}

// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const PlataformaTransaccionalDistribuidaEventDrivenCommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.object({

  })
});

export type PlataformaTransaccionalDistribuidaEventDrivenCommand = z.infer<typeof PlataformaTransaccionalDistribuidaEventDrivenCommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface IPlataformaTransaccionalDistribuidaEventDrivenRepository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}

// --------------------------------------------------------------------------
// CQRS + Event Sourcing Infrastructure Contracts
// --------------------------------------------------------------------------
export interface IAggregateRoot<T> {
  id: string;
  version: number;
  uncommittedEvents: IDomainEvent[];
  apply(event: IDomainEvent): void;
  clearUncommittedEvents(): void;
}

export interface IEventStore {
  saveEvents(aggregateId: string, events: IDomainEvent[], expectedVersion: number): Promise<void>;
  getEventsForAggregate(aggregateId: string): Promise<IDomainEvent[]>;
}

export interface ISnapshotStore<T> {
  getSnapshot(aggregateId: string): Promise<{ version: number; state: T } | null>;
  saveSnapshot(aggregateId: string, version: number, state: T): Promise<void>;
}
