version: '3.8'

services:
  # Host Environment SDK Isolation Sandbox
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: transactional-system-app
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://dev_user:dev_password@postgresql:5432/transactional-system_db
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  # Database Service (postgresql)
  postgresql:
    image: postgres:16-alpine
    container_name: transactional-system-db
    restart: always
    environment:
      POSTGRES_DB: transactional-system_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  
  # Message Broker
  sqs:
    image: localstack/localstack
    container_name: transactional-system-mq
    restart: always
    ports:
      - "4566:4566"
      
  

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: transactional-system-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
