<?php

declare(strict_types=1);

/* ==========================================================================
   Generated Domain Contracts & PHP DTOs
   Feature: Plataforma Transaccional Distribuida Event-Driven
   Stack: PHP 8.2 + native-php + pdo
   Generated by gherkin-ai CLI v1.5.0
   ========================================================================== */

namespace App\Domain\Contracts\PlataformaTransaccionalDistribuidaEventDriven;

use DateTimeImmutable;

// --------------------------------------------------------------------------
// 1. Base Domain Event Interface
// --------------------------------------------------------------------------
interface IDomainEvent
{
    public function getEventId(): string;
    public function getOccurredOn(): DateTimeImmutable;
    public function getEventType(): string;
}

readonly class Event1 implements IDomainEvent
{
    public string $eventType = 'aOrderCreatedeventispublishedwithauniqueCorrelationId';

    public function __construct(
        public string $eventId,
        public DateTimeImmutable $occurredOn,
        public array $payload = []
    ) {}

    public function getEventId(): string { return $this->eventId; }
    public function getOccurredOn(): DateTimeImmutable { return $this->occurredOn; }
    public function getEventType(): string
    {
        return 'aOrderCreatedeventispublishedwithauniqueCorrelationId';
    }
}

readonly class Event2 implements IDomainEvent
{
    public string $eventType = 'anexistingwebhookeventwithMessageIdABC123';

    public function __construct(
        public string $eventId,
        public DateTimeImmutable $occurredOn,
        public array $payload = []
    ) {}

    public function getEventId(): string { return $this->eventId; }
    public function getOccurredOn(): DateTimeImmutable { return $this->occurredOn; }
    public function getEventType(): string
    {
        return 'anexistingwebhookeventwithMessageIdABC123';
    }
}

readonly class Event3 implements IDomainEvent
{
    public string $eventType = 'thesystemreceivesaduplicatewebhookeventwithMessageIdABC123';

    public function __construct(
        public string $eventId,
        public DateTimeImmutable $occurredOn,
        public array $payload = []
    ) {}

    public function getEventId(): string { return $this->eventId; }
    public function getOccurredOn(): DateTimeImmutable { return $this->occurredOn; }
    public function getEventType(): string
    {
        return 'thesystemreceivesaduplicatewebhookeventwithMessageIdABC123';
    }
}

readonly class Event4 implements IDomainEvent
{
    public string $eventType = 'thesystemignorestheduplicateevent';

    public function __construct(
        public string $eventId,
        public DateTimeImmutable $occurredOn,
        public array $payload = []
    ) {}

    public function getEventId(): string { return $this->eventId; }
    public function getOccurredOn(): DateTimeImmutable { return $this->occurredOn; }
    public function getEventType(): string
    {
        return 'thesystemignorestheduplicateevent';
    }
}

readonly class Event5 implements IDomainEvent
{
    public string $eventType = 'anOutboxeventissafelypersisted';

    public function __construct(
        public string $eventId,
        public DateTimeImmutable $occurredOn,
        public array $payload = []
    ) {}

    public function getEventId(): string { return $this->eventId; }
    public function getOccurredOn(): DateTimeImmutable { return $this->occurredOn; }
    public function getEventType(): string
    {
        return 'anOutboxeventissafelypersisted';
    }
}

readonly class Event6 implements IDomainEvent
{
    public string $eventType = 'theCustomerUpdatedeventispublished';

    public function __construct(
        public string $eventId,
        public DateTimeImmutable $occurredOn,
        public array $payload = []
    ) {}

    public function getEventId(): string { return $this->eventId; }
    public function getOccurredOn(): DateTimeImmutable { return $this->occurredOn; }
    public function getEventType(): string
    {
        return 'theCustomerUpdatedeventispublished';
    }
}

// --------------------------------------------------------------------------
// 2. Command DTO Class (Readonly PHP 8.2)
// --------------------------------------------------------------------------
readonly class PlataformaTransaccionalDistribuidaEventDrivenCommand
{
    public function __construct(
        public string $requestId,
        public DateTimeImmutable $timestamp,
        public array $payload
    ) {}
}

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
interface IPlataformaTransaccionalDistribuidaEventDrivenRepository
{
    public function findById(string $id): mixed;
    public function save(mixed $entity): void;
    public function delete(string $id): void;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
interface IEventPublisher
{
    public function publish(IDomainEvent $event): void;
}
