// Reqnroll step definitions for "Transactional System" (generated by gherkin-ai).
// Each step is wired to the feature and pending until implemented (reqnroll.json ignores pending steps).
using transactionalsystem.Domain.Kernel;
using Reqnroll;

namespace transactionalsystem.Tests.Steps;

[Binding]
public class TransactionalSystemStepDefinitions
{
    private TransactionalSystemAggregate _aggregate = new("scenario-aggregate");

    [BeforeScenario]
    public void ResetAggregate() => _aggregate = new TransactionalSystemAggregate("scenario-aggregate");

    [Given("a valid transactional system request with required payload")]
    public void given_a_valid_transactional_system_request_with_required_payload()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }

    [When("processing transactional system request")]
    public void when_processing_transactional_system_request()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }

    [Then("the system responds with HTTP status 200 OK")]
    public void then_the_system_responds_with_http_status_200_ok()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }

    [Then("stores record in database")]
    public void then_stores_record_in_database()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }

    [Then("emits a \"TransactionalSystemProcessed\" domain event")]
    public void then_emits_a_transactional_system_processed_domain_event()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }

    [Given("an invalid transactional system request with missing fields")]
    public void given_an_invalid_transactional_system_request_with_missing_fields()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }

    [Then("the system responds with HTTP status 400 Bad Request")]
    public void then_the_system_responds_with_http_status_400_bad_request()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }

    [Then("returns validation error details")]
    public void then_returns_validation_error_details()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }
}
