// Domain kernel for "Transactional System" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
namespace transactionalsystem.Domain.Kernel;

public sealed class DomainValidationException : Exception
{
    public DomainValidationException(string message) : base(message) { }
}

public static class TransactionalSystemStates
{
    public const string PENDING = "PENDING";
    public const string PROCESSING = "PROCESSING";
    public const string FAILED = "FAILED";
}

public static class TransactionalSystemEventTypes
{
    public const string TransactionalSystemProcessed = "TransactionalSystemProcessed";
}

public sealed record TransactionalSystemCommand(string Id, IReadOnlyDictionary<string, object?>? Payload = null);

public sealed record TransactionalSystemDomainEvent(string Type, string AggregateId, long Version, DateTimeOffset OccurredOn, IReadOnlyDictionary<string, object?> Payload);

public sealed class TransactionalSystemAggregate
{
    private readonly List<TransactionalSystemDomainEvent> _pendingEvents = new();

    public TransactionalSystemAggregate(string id)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new DomainValidationException("TransactionalSystem id is required");
        Id = id;
    }

    public string Id { get; }
    public string State { get; private set; } = TransactionalSystemStates.PENDING;
    public long Version { get; private set; }

    /// <summary>Events recorded since the aggregate was loaded (to be saved via the outbox).</summary>
    public IReadOnlyList<TransactionalSystemDomainEvent> PendingEvents => _pendingEvents;

    public TransactionalSystemDomainEvent ProcessTransactionalSystem(TransactionalSystemCommand command)
    {
        AssertValid(command);
        return Record(TransactionalSystemEventTypes.TransactionalSystemProcessed, command.Payload);
    }

    private void AssertValid(TransactionalSystemCommand command)
    {
        if (command is null || string.IsNullOrWhiteSpace(command.Id)) throw new DomainValidationException("Command id is required");
        if (command.Id != Id) throw new DomainValidationException($"Command targets {command.Id}, not {Id}");
    }

    private TransactionalSystemDomainEvent Record(string type, IReadOnlyDictionary<string, object?>? payload)
    {
        Version += 1;
        var @event = new TransactionalSystemDomainEvent(type, Id, Version, DateTimeOffset.UtcNow, payload ?? new Dictionary<string, object?>());
        _pendingEvents.Add(@event);
        return @event;
    }
}
